---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, echo=FALSE}
## Start simulations with a range of initial population sizes and trait values
## ESS is bmax* = 1/(2*slope) = 3
## Ecological equilibrium N* = (bmax-s*bmax^2)/(bs+ds)
source("logistic_GEM.R")
library(tidyverse)
library(parallel)

## Start at the ecological equilibrium given the trait value
bmax_seq <- seq(0.5,5.5,0.5)
s <- 1/6
bs <- ds <- 0.025
N0_seq <- sapply(bmax_seq, function(b) (b-s*b^2)/(bs+ds))
output1 <- vector(mode='list', length=length(bmax_seq))
tin = Sys.time()
for (i in 1:length(bmax_seq)) {
    set.seed(1343421)
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=100, N0=N0_seq[i], traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i) -> output1[[i]]
}
tout = Sys.time()
tout-tin


## Start at the same population size, regardless of the initial trait, and one that is well below the expected eco-evolutionary ecological equilibrium of 30
tin = Sys.time()
output2 <- vector(mode='list', length=length(bmax_seq))
for (i in 1:length(bmax_seq)) {
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=1000, N0=10, traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i)  -> output2[[i]]
}
tout = Sys.time()
tout-tin

out <- vector(mode='list', length=100)
for (j in 1:100)
    out[[j]] <- logistic_GEM(seed=seeds[j], dt=1, tmax=100, N0=22, traitmean=1.5, traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s)



## Start at the same population size, regardless of the initial trait, and one that is well above the expected eco-evolutionary ecological equilibrium of 30
tin = Sys.time()
output3 <- vector(mode='list', length=length(bmax_seq))
for (i in 2:length(bmax_seq)) {
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=1000, N0=50, traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i)  -> output3[[i]]
}
tout = Sys.time()
tout-tin

output1 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",signif(N0_seq[set],3),sep="")) -> out1

output2 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",10,sep="")) -> out2

output3 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",50,sep=""))  -> out3

saveRDS(out1, file="Logistic_GEM_bs=ds=025_varying_b0_and_N0.RDS")
saveRDS(out2, file="Logistic_GEM_bs=ds=025_varying_b0_N0=10.RDS")
saveRDS(out3, file="Logistic_GEM_bs=ds=025_varying_b0_N0=50.RDS")

## Start at the ecological equilibrium given the trait value
bmax_seq <- seq(0.5,5.5,0.5)
s <- 1/6
bs <- ds <- 0.0375
N0_seq <- sapply(bmax_seq, function(b) (b-s*b^2)/(bs+ds))
output1 <- vector(mode='list', length=length(bmax_seq))
tin = Sys.time()
for (i in 1:length(bmax_seq)) {
    set.seed(1343421)
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=100, N0=N0_seq[i], traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i) -> output1[[i]]
}
tout = Sys.time()
tout-tin


## Start at the same population size, regardless of the initial trait, and one that is well below the expected eco-evolutionary ecological equilibrium of 30
tin = Sys.time()
output2 <- vector(mode='list', length=length(bmax_seq))
for (i in 1:length(bmax_seq)) {
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=1000, N0=10, traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i)  -> output2[[i]]
}
tout = Sys.time()
tout-tin

out <- vector(mode='list', length=100)
for (j in 1:100)
    out[[j]] <- logistic_GEM(seed=seeds[j], dt=1, tmax=100, N0=22, traitmean=1.5, traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s)



## Start at the same population size, regardless of the initial trait, and one that is well above the expected eco-evolutionary ecological equilibrium of 30
tin = Sys.time()
output3 <- vector(mode='list', length=length(bmax_seq))
for (i in 2:length(bmax_seq)) {
    seeds <- floor(runif(100, 1, 1e5))
    mclapply(seeds,
             function(s) logistic_GEM(seed=s, dt=1, tmax=1000, N0=50, traitmean=bmax_seq[i], traitcv=0.3, h2=0.75, bs=bs, ds=ds, slope=s),
             mc.cores=8
    ) -> out 
    ## create a dataframe storing the results (the median population size across the replicates and the median mean trait)
    data.frame(time=0:1000,
               N=lapply(out, function(l) lapply(l$traits, function(j) ifelse(length(j)>0,length(j),NA)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               b=lapply(out, function(l) lapply(l$traits, function(t) mean(t,na.rm=TRUE)) %>% unlist) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) median(r,na.rm=TRUE)),
               selGrad=lapply(out, function(l) 1-2*s*(lapply(l$traits, mean) %>% unlist)) %>% do.call("cbind.data.frame",.) %>% apply(.,1,function(r) mean(r,na.rm=TRUE)),
               cumExtinct=cumsum(sapply(1:1001, function(t) sum((lapply(out, function(l) min(which((lapply(l$traits, length) %>% unlist)==0))) %>% unlist)==t))),
               set=i)  -> output3[[i]]
}
tout = Sys.time()
tout-tin

output1 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",signif(N0_seq[set],3),sep="")) -> out1

output2 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",10,sep="")) -> out2

output3 %>% 
    do.call("rbind.data.frame",.) %>% 
    mutate(., init=paste("b0=",signif(bmax_seq[set],3),"\n","N0=",50,sep=""))  -> out3

saveRDS(out1, file="Logistic_GEM_bs=ds=0375_varying_b0_and_N0.RDS")
saveRDS(out2, file="Logistic_GEM_bs=ds=0375_varying_b0_N0=10.RDS")
saveRDS(out3, file="Logistic_GEM_bs=ds=0375_varying_b0_N0=50.RDS")
```

```{r, fig.height=5, fig.width=9, units='in', res=300}
out1 <- readRDS("Logistic_GEM_bs=ds=025_varying_b0_and_N0.RDS")
out2 <- readRDS("Logistic_GEM_bs=ds=025_varying_b0_N0=10.RDS")
out3 <- readRDS("Logistic_GEM_bs=ds=025_varying_b0_N0=50.RDS")

out1 %>% pivot_longer(c(N,b), names_to="Var", values_to="Val") -> o1

mean_Val <- o1 %>% group_by(init, Var) %>% summarize(meanVal=mean(tail(Val,100)))

ggplot(o1, aes(x=time, y=Val)) +
  facet_grid(Var~init,scales="free_y") + geom_line() +
  geom_hline(aes(yintercept=meanVal, col="red"), mean_Val) +
  geom_hline()
  theme_bw()
```